// <auto-generated />
namespace Gabby.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class db4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db4));
        
        string IMigrationMetadata.Id
        {
            get { return "201912170436359_db4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
